# SPDX-License-Identifier: GPL-2.0

KBUILD_EXTRA_WARN=1
DTC_FLAGS += -Wno-graph_child_address

subdir-y += google

dtb-$(CONFIG_ARCH_EXYNOS) += \
	exynos5433-tm2.dtb		\
	exynos5433-tm2e.dtb		\
	exynos7-espresso.dtb		\
	exynos7885-jackpotlte.dtb	\
	exynos850-e850-96.dtb		\
	exynosautov9-sadk.dtb		\
	exynosautov920-sadk.dtb
